version: 2
comment:
  layout: "reach, diff, flags, files"
  behavior: default

coverage:
  precision: 2  
  round: down    
  range: "70...100"  
  status:
    project: 
      default:
        target: 80%  
    patch:
      default:
        target: 70%  h

flags:
  1.22.6:
    paths:
      - coverage.out

ignore:
  - "**/vendor/**"
  - "**/test/**"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"  
  behavior: default  
