version: '3'

services:
  postgres_test:
    image: postgres:14-alpine
    container_name: order-service-postgres-test
    env_file:
      - .env.test
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - order-service-test

  rabbitmq_test:
    image: rabbitmq:3-management
    container_name: order-service-rabbitmq-test
    env_file:
      - .env.test
    ports:
      - "${BROKER_PORT}:5672"
      - "${BROKER_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - order-service-test

networks:
  order-service-test:
    driver: bridge

