name: Go CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
      security-events: write

    strategy:
      matrix:
        go-version: ['1.22.6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true  

      - name: Cache golangci-lint
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start test database
        run: |
          docker compose -f docker-compose-test.yml up -d postgres_test
          # Aguarda o postgres ficar pronto
          timeout 30s bash -c 'until docker compose exec -T postgres_test pg_isready; do sleep 1; done'

      - name: Run Tests with Coverage
        run: |
          # Aguarda mais alguns segundos para garantir que o banco está pronto
          sleep 5
          go test ./... -coverprofile=coverage.out -json
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders_test

      - name: Stop test database
        if: always()
        run: docker compose -f docker-compose-test.yml down

      - name: Filter coverage files to exclude test files
        run: |
          grep -v '_test.go' coverage.out > filtered-coverage.out

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: filtered-coverage.out
          flags: ${{ matrix.go-version }}
          name: Code Coverage
          slug: rafael-silva-menezes/caju-flow-order-service

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload Snyk Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
